import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Achievement from '#models/achievement'

export default class extends BaseSeeder {
  async run() {
    await Achievement.createMany([
      {
        code: 'first_card',
        name: 'Première Carte',
        description: 'Créer votre première carte',
        icon: 'add-circle',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'cards_created', target: 1 },
      },
      {
        code: 'card_collector_10',
        name: 'Collectionneur Débutant',
        description: 'Créer 10 cartes',
        icon: 'albums',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'cards_created', target: 10 },
      },
      {
        code: 'card_collector_50',
        name: 'Collectionneur Confirmé',
        description: 'Créer 50 cartes',
        icon: 'albums',
        category: 'cards',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'cards_created', target: 50 },
      },
      {
        code: 'card_collector_100',
        name: 'Collectionneur Expert',
        description: 'Créer 100 cartes',
        icon: 'library',
        category: 'cards',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'cards_created', target: 100 },
      },
      {
        code: 'card_collector_500',
        name: 'Bibliothécaire',
        description: 'Créer 500 cartes',
        icon: 'library',
        category: 'cards',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'cards_created', target: 500 },
      },

      {
        code: 'first_deck',
        name: 'Premier Deck',
        description: 'Créer votre premier deck',
        icon: 'folder',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'decks_created', target: 1 },
      },
      {
        code: 'deck_creator_5',
        name: 'Organisateur',
        description: 'Créer 5 decks',
        icon: 'folder-open',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'decks_created', target: 5 },
      },
      {
        code: 'deck_creator_10',
        name: 'Archiviste',
        description: 'Créer 10 decks',
        icon: 'folders',
        category: 'cards',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'decks_created', target: 10 },
      },

      {
        code: 'first_silver',
        name: 'Première Étoile',
        description: 'Obtenir votre première carte Argent',
        icon: 'ribbon',
        category: 'collection',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'card_status', status: 'silver', target: 1 },
      },
      {
        code: 'silver_collector_10',
        name: 'Argentier',
        description: 'Obtenir 10 cartes Argent',
        icon: 'ribbon',
        category: 'collection',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'card_status', status: 'silver', target: 10 },
      },
      {
        code: 'first_gold',
        name: "Touche d'Or",
        description: 'Obtenir votre première carte Or',
        icon: 'trophy',
        category: 'collection',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'card_status', status: 'gold', target: 1 },
      },
      {
        code: 'gold_collector_10',
        name: "Chercheur d'Or",
        description: 'Obtenir 10 cartes Or',
        icon: 'trophy',
        category: 'collection',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'card_status', status: 'gold', target: 10 },
      },
      {
        code: 'first_platinum',
        name: 'Platine Parfait',
        description: 'Obtenir votre première carte Platine',
        icon: 'medal',
        category: 'collection',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'card_status', status: 'platinum', target: 1 },
      },
      {
        code: 'platinum_collector_5',
        name: 'Platine Club',
        description: 'Obtenir 5 cartes Platine',
        icon: 'medal',
        category: 'collection',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'card_status', status: 'platinum', target: 5 },
      },
      {
        code: 'first_ruby',
        name: 'Rubis Éclatant',
        description: 'Obtenir votre première carte Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'card_status', status: 'ruby', target: 1 },
      },
      {
        code: 'ruby_collector_5',
        name: 'Chasseur de Rubis',
        description: 'Obtenir 5 cartes Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'card_status', status: 'ruby', target: 5 },
      },
      {
        code: 'ruby_collector_25',
        name: 'Maître des Rubis',
        description: 'Obtenir 25 cartes Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: true,
        conditions: { type: 'card_status', status: 'ruby', target: 25 },
      },

      {
        code: 'first_training',
        name: 'Premier Pas',
        description: "Compléter votre première session d'entraînement",
        icon: 'fitness',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 1 },
      },
      {
        code: 'training_10',
        name: 'Habitué',
        description: "Compléter 10 sessions d'entraînement",
        icon: 'fitness',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 10 },
      },
      {
        code: 'training_50',
        name: 'Athlète Mental',
        description: "Compléter 50 sessions d'entraînement",
        icon: 'barbell',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 50 },
      },
      {
        code: 'training_100',
        name: 'Machine à Apprendre',
        description: "Compléter 100 sessions d'entraînement",
        icon: 'barbell',
        category: 'training',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 100 },
      },
      {
        code: 'training_500',
        name: 'Légende Vivante',
        description: "Compléter 500 sessions d'entraînement",
        icon: 'star',
        category: 'training',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 500 },
      },
      {
        code: 'speedrun_10',
        name: 'Sprinter',
        description: 'Compléter 10 sessions en mode Speed Run',
        icon: 'flash',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'speedrun', target: 10 },
      },
      {
        code: 'speedrun_50',
        name: 'Éclair',
        description: 'Compléter 50 sessions en mode Speed Run',
        icon: 'flash',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'speedrun', target: 50 },
      },
      {
        code: 'perfect_5',
        name: 'Sans Faute',
        description: 'Compléter 5 sessions parfaites en mode Perfect',
        icon: 'checkmark-done',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'perfect', target: 5 },
      },
      {
        code: 'perfect_25',
        name: 'Perfectionniste',
        description: 'Compléter 25 sessions parfaites en mode Perfect',
        icon: 'checkmark-done-circle',
        category: 'training',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'perfect', target: 25 },
      },
      {
        code: 'streak_mode_10',
        name: 'Survivant',
        description: 'Compléter 10 sessions en mode Streak',
        icon: 'heart',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'streak', target: 10 },
      },
      {
        code: 'timeattack_10',
        name: 'Contre la Montre',
        description: 'Compléter 10 sessions en mode Time Attack',
        icon: 'timer',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'timeattack', target: 10 },
      },
      {
        code: 'streak_10',
        name: 'En Forme',
        description: 'Atteindre une série de 10 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'streak', target: 10 },
      },
      {
        code: 'streak_25',
        name: 'En Feu',
        description: 'Atteindre une série de 25 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'streak', target: 25 },
      },
      {
        code: 'streak_50',
        name: 'Inarrêtable',
        description: 'Atteindre une série de 50 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'streak', target: 50 },
      },
      {
        code: 'streak_100',
        name: 'Infaillible',
        description: 'Atteindre une série de 100 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'streak', target: 100 },
      },
      {
        code: 'correct_100',
        name: 'Bon Début',
        description: 'Répondre correctement à 100 cartes',
        icon: 'checkmark-circle',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'total_correct', target: 100 },
      },
      {
        code: 'correct_500',
        name: 'Érudit',
        description: 'Répondre correctement à 500 cartes',
        icon: 'checkmark-circle',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'total_correct', target: 500 },
      },
      {
        code: 'correct_1000',
        name: 'Savant',
        description: 'Répondre correctement à 1000 cartes',
        icon: 'school',
        category: 'training',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'total_correct', target: 1000 },
      },
      {
        code: 'correct_5000',
        name: 'Génie',
        description: 'Répondre correctement à 5000 cartes',
        icon: 'school',
        category: 'training',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'total_correct', target: 5000 },
      },
      {
        code: 'night_owl',
        name: 'Oiseau de Nuit',
        description: 'Étudier entre minuit et 5h du matin',
        icon: 'moon',
        category: 'training',
        rarity: 'rare',
        isSecret: true,
        conditions: { type: 'time_of_day', startHour: 0, endHour: 5, target: 1 },
      },
      {
        code: 'early_bird',
        name: 'Lève-Tôt',
        description: 'Étudier entre 5h et 7h du matin',
        icon: 'sunny',
        category: 'training',
        rarity: 'rare',
        isSecret: true,
        conditions: { type: 'time_of_day', startHour: 5, endHour: 7, target: 1 },
      },
      {
        code: 'marathon',
        name: 'Marathonien',
        description: 'Compléter 10 sessions en une journée',
        icon: 'walk',
        category: 'training',
        rarity: 'epic',
        isSecret: true,
        conditions: { type: 'daily_sessions', target: 10 },
      },
      {
        code: 'comeback',
        name: 'Le Retour',
        description: "Revenir après 7 jours d'absence",
        icon: 'refresh',
        category: 'training',
        rarity: 'rare',
        isSecret: true,
        conditions: { type: 'comeback_days', target: 7 },
      },
    ])
  }
}
