import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Achievement from '#models/achievement'

export default class extends BaseSeeder {
  async run() {
    await Achievement.createMany([
      {
        code: 'first_card',
        name: 'Première Carte',
        description: 'Créer votre première carte',
        icon: 'add-circle',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'cards_created', target: 1 },
      },
      {
        code: 'card_collector_10',
        name: 'Collectionneur Débutant',
        description: 'Créer 10 cartes',
        icon: 'albums',
        category: 'cards',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'cards_created', target: 10 },
      },
      {
        code: 'card_collector_50',
        name: 'Collectionneur Confirmé',
        description: 'Créer 50 cartes',
        icon: 'albums',
        category: 'cards',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'cards_created', target: 50 },
      },
      {
        code: 'card_collector_100',
        name: 'Collectionneur Expert',
        description: 'Créer 100 cartes',
        icon: 'library',
        category: 'cards',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'cards_created', target: 100 },
      },
      {
        code: 'card_collector_500',
        name: 'Bibliothécaire',
        description: 'Créer 500 cartes',
        icon: 'library',
        category: 'cards',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'cards_created', target: 500 },
      },

      {
        code: 'first_silver',
        name: 'Première Étoile',
        description: 'Obtenir votre première carte Argent',
        icon: 'ribbon',
        category: 'collection',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'card_status', status: 'silver', target: 1 },
      },
      {
        code: 'first_gold',
        name: "Touche d'Or",
        description: 'Obtenir votre première carte Or',
        icon: 'trophy',
        category: 'collection',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'card_status', status: 'gold', target: 1 },
      },
      {
        code: 'first_platinum',
        name: 'Platine Parfait',
        description: 'Obtenir votre première carte Platine',
        icon: 'medal',
        category: 'collection',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'card_status', status: 'platinum', target: 1 },
      },
      {
        code: 'first_ruby',
        name: 'Rubis Éclatant',
        description: 'Obtenir votre première carte Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'card_status', status: 'ruby', target: 1 },
      },
      {
        code: 'ruby_collector_5',
        name: 'Chasseur de Rubis',
        description: 'Obtenir 5 cartes Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'card_status', status: 'ruby', target: 5 },
      },
      {
        code: 'ruby_collector_25',
        name: 'Maître des Rubis',
        description: 'Obtenir 25 cartes Ruby',
        icon: 'diamond',
        category: 'collection',
        rarity: 'legendary',
        isSecret: true,
        conditions: { type: 'card_status', status: 'ruby', target: 25 },
      },

      {
        code: 'first_training',
        name: 'Premier Pas',
        description: "Compléter votre première session d'entraînement",
        icon: 'fitness',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 1 },
      },
      {
        code: 'training_10',
        name: 'Habitué',
        description: "Compléter 10 sessions d'entraînement",
        icon: 'fitness',
        category: 'training',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 10 },
      },
      {
        code: 'training_50',
        name: 'Athlète Mental',
        description: "Compléter 50 sessions d'entraînement",
        icon: 'barbell',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 50 },
      },
      {
        code: 'training_100',
        name: 'Machine à Apprendre',
        description: "Compléter 100 sessions d'entraînement",
        icon: 'barbell',
        category: 'training',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'trainings_completed', target: 100 },
      },
      {
        code: 'speedrun_master',
        name: 'Éclair',
        description: 'Compléter 25 sessions en mode Speed Run',
        icon: 'flash',
        category: 'training',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'speedrun', target: 25 },
      },
      {
        code: 'perfect_master',
        name: 'Perfectionniste',
        description: 'Compléter 10 sessions parfaites en mode Perfect',
        icon: 'diamond',
        category: 'training',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'trainings_completed', mode: 'perfect', target: 10 },
      },

      {
        code: 'streak_10',
        name: 'En Forme',
        description: 'Atteindre une série de 10 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'common',
        isSecret: false,
        conditions: { type: 'streak', target: 10 },
      },
      {
        code: 'streak_25',
        name: 'En Feu',
        description: 'Atteindre une série de 25 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'rare',
        isSecret: false,
        conditions: { type: 'streak', target: 25 },
      },
      {
        code: 'streak_50',
        name: 'Inarrêtable',
        description: 'Atteindre une série de 50 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'epic',
        isSecret: false,
        conditions: { type: 'streak', target: 50 },
      },
      {
        code: 'streak_100',
        name: 'Légende',
        description: 'Atteindre une série de 100 bonnes réponses',
        icon: 'flame',
        category: 'streaks',
        rarity: 'legendary',
        isSecret: false,
        conditions: { type: 'streak', target: 100 },
      },

      {
        code: 'night_owl',
        name: 'Oiseau de Nuit',
        description: 'Étudier entre minuit et 5h du matin',
        icon: 'moon',
        category: 'training',
        rarity: 'rare',
        isSecret: true,
        conditions: { type: 'time_of_day', startHour: 0, endHour: 5, target: 1 },
      },
      {
        code: 'early_bird',
        name: 'Lève-Tôt',
        description: 'Étudier entre 5h et 7h du matin',
        icon: 'sunny',
        category: 'training',
        rarity: 'rare',
        isSecret: true,
        conditions: { type: 'time_of_day', startHour: 5, endHour: 7, target: 1 },
      },
      {
        code: 'marathon',
        name: 'Marathonien',
        description: 'Compléter 10 sessions en une journée',
        icon: 'walk',
        category: 'training',
        rarity: 'epic',
        isSecret: true,
        conditions: { type: 'daily_sessions', target: 10 },
      },
    ])
  }
}
